homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 102
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  ssl_certificate: /home/homeassistant/.homeassistant/certificate.pem
  ssl_key: /home/homeassistant/.homeassistant/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# MQTT broker mosquitto
mqtt:
  broker: 127.0.0.1

# Track the sun
sun:

# ffmpeg to manage camera ip
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# ONVIF1 camera (rstp)
camera:
  - platform: onvif
    host: !secret ip_camera_1
    username: !secret user_camera_1
    password: !secret pass_camera_1

binary_sensor:
  - platform: ffmpeg_motion
    input: !secret input_camera_1

sensor:
  - platform: waze_travel_time
    origin: !secret home_waze_city
    destination: !secret work_waze_city
    region: 'EU'
  - platform: mqtt
    state_topic: "sensor/temperature"
    name: "Température"
    qos: 0
    unit_of_measurement: "°C"
    #value_template: '{{ payload }}'
  - platform: mqtt
    state_topic: "sensor/humidity"
    name: "Humidité"
    qos: 0
    unit_of_measurement: "%"
    #value_template: '{{ payload }}'
  - platform: mqtt
    state_topic: "sensor/living_temp"
    name: "Température salon"
    qos: 0
    unit_of_measurement: "°C"
    #value_template: '{{ payload }}'
  - platform: mqtt
    state_topic: "sensor/living_hum"
    name: "Humidité salon"
    qos: 0
    unit_of_measurement: "%"
    #value_template: '{{ payload }}'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
  - platform: template
    sensors:
      tp_link_amps:
        value_template: '{{ states.switch.tplink_switch_hs110.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: 'A'
      tp_link_watts:
        value_template: '{{ states.switch.tplink_switch_hs110.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
      tp_link_kw:
        value_template: '{{ states.switch.tplink_switch_hs110.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'
      tp_link_volts:
        value_template: '{{ states.switch.tplink_switch_hs110.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: 'V'

# Weather prediction
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_key
    name: !secret home_city

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

switch:
  - platform: tplink
    host: 192.168.31.246
    name: tplink_switch_hs110

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
